app:
  models:
    user:
      name_max_length: 50
      email_max_length: 255
      password_max_length: 6
      users_per_page: 5
      avatar_size: 40
      reset_password_limit: 2
    micropost:
      content_max_length: 140
      microposts_per_page: 5
      picture_max_size: 5
  helper:
    users_helper:
      avatar_size: 80
    microposts_helper:
      avatar_size: 50
  yes_remember_me: 1
  developement:
    host: localhost:3000
    action_mailer:
      address: smtp.gmail.com
      port: 587
      domain: example.com
  production:
    host: <your heroku app>.herokuapp.com
    action_mailer:
      address: smtp.sendgrid.net
      port: 587
      domain: heroku.com
  picture_uploader:
    size_limit: [400, 400]
