app:
  models:
    user:
      name_max_length: 50
      email_max_length: 255
      password_max_length: 6
      users_per_page: 5
      avatar_size: 40
  helper:
    users_helper:
      avatar_size: 80
  yes_remember_me: 1
  paginate:
